# 공통
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/sample;mode=mysql
    driver-class-name: org.h2.Driver
    username: sample
    password: sample
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  cache:
    type: redis
  sql:
    init:
      mode: always
  devtools:
    livereload:
      enabled: true

# Actuator 보안 설정 샘플 (https://techblog.woowahan.com/9232)
management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: info, health
  server:
    port: 10000
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

logging:
  file:
    path: log
    name: log/sample-project.log
  logback:
    rollingpolicy:
      max-history: 3
  level:
    root: info

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: alpha

resilience4j:
  circuitbreaker:
    configs:
      default:
        minimum-number-of-calls: 5
        sliding-window-size: 3
    instances:
      testCircuitBreaker:
        base-config: default
